#!/usr/bin/env php
<?php

if($argv[1]=='m'){
	$tpl=file_get_contents("doc/stubs/model.stub");
	for ($i=2;$i<$argc;$i++){
		createModelFile($argv[$i],$tpl);
	}
}else if($argv[1]=='a'){
	$tpl=file_get_contents("doc/stubs/adminController.stub");
	for ($i=2;$i<$argc;$i++){
		createControllerFile($argv[$i],$tpl);
	}
}


function createModelFile($fname,$content)
{
	$con=str_replace("{%className%}", $fname, $content);
	create_file("application/common/model/".$fname.".php",$con);
}


function createControllerFile($fname,$content)
{
	$con=str_replace("{%className%}", $fname, $content);
	create_file("application/admin/controller/".$fname.".php",$con);
}
function create_file($fname,$content)
{	
	if(!file_exists($fname)){
		$myfile = fopen($fname, "w");
		fwrite($myfile, $content);
		fclose($myfile);
		echo "成功创建文件：".$fname;
	}
	
}