#!/usr/bin/env php
<?php
if($argc>1){
	switch ($argv[1]) {
		case 'mm':
		$tpl=file_get_contents("doc/stubs/model.stub");
		for ($i=2;$i<$argc;$i++){
			createModelFile($argv[$i],$tpl);
		}
		break;
		case 'ma':
		$tpl=file_get_contents("doc/stubs/adminController.stub");
		for ($i=2;$i<$argc;$i++){
			createControllerFile($argv[$i],$tpl);
		}
		break;
		case 'm':
		$mtpl=file_get_contents("doc/stubs/model.stub");
		$ctpl=file_get_contents("doc/stubs/adminController.stub");
		$tables=getTables();
		foreach ($tables as $key => $table) {
			$nameArray=explode('_', $table['name']);
			$name=ucfirst(strtolower($nameArray[0]));
			if(count($nameArray)>1){
				$name=strtolower($nameArray[0]).'/';
				for ($i=1; $i <count($nameArray) ; $i++) { 
					$name.=ucfirst(strtolower($nameArray[$i]));
				}
			}
			createControllerFile($name,$ctpl,$table['comment']);
			//
			createModelFile($name,$mtpl,$table['comment']);
		}
		break;
	}
}
else{
	showMsg('mm modeName -- 创建model');
	showMsg('ma controllerName --创建');
}
function getTables()
{
	$config=include('application/database.php');
	$host=$config['hostname'];
	$database=$config['database'];
	$dsn = "mysql:host=$host;dbname=$database";
	$db = new PDO($dsn, $config['username'], $config['password']);
	$res = $db->prepare("SHOW TABLES");
	$res->execute();
	$result=$res->fetchAll();
	$tables=array();
	foreach ($result as $key => $row) {
		$tbName=$row[0];
		$res2 = $db->prepare("show table status like '$tbName'");
		$res2->execute();
		$result2=$res2->fetchAll();
		$table['name']=$tbName;
		if($result2){
			$table['comment']=$result2[0][17];
		}else{
			$table['comment']='';
		}
		$tables[]=$table;
	}
	$db = null;
	return $tables;
}
function showMsg($msg)
{
	echo iconv("utf-8","gb2312","$msg \r\n");
}

function createModelFile($fname,$content,$comment='')
{
	create_file_build($fname,$content,'application/common/model/',$comment);
}

function createControllerFile($fname,$content,$comment='')
{
	create_file_build($fname,$content,'application/admin/controller/',$comment);
}

function create_file_build($fname,$content,$file_dir,$comment)
{
	$names=explode('/', $fname);
	$fileName=$names[count($names)-1];
	$fileName=ucfirst($fileName);
	$con=str_replace("{%className%}", $fileName, $content);
	unset($names[count($names)-1]);
	$dir=implode('/',$names);
	if(!empty($dir)){
		$dir="\\".$dir;
	}
	if(empty($comment)){
		$comment=str_replace('/','_',$fname);
	}
	$con=$con=str_replace("{%dir%}",$dir, $con);
	$con=$con=str_replace("{%comment%}", iconv("gbk","utf-8",$comment), $con);
	$fname=implode('/',$names).'/'.$fileName;
	create_file($file_dir.$fname.".php",$con);
}
function create_file($fname,$content)
{	
	
	if(!file_exists($fname)){
		create_dir($fname);
		$myfile = fopen($fname, "w");
		fwrite($myfile, $content);
		fclose($myfile);
		showMsg("成功创建文件：".$fname);
	}
}
function create_dir($fname)
{
	$names=explode('/', $fname);
	$dir='';
	for ($i=0; $i <count($names)-1; $i++) { 
		if($i==0){
			$dir=$names[0];
		}else{
			$dir.='/'.$names[$i];
		}
		if (!is_dir($dir)){ 
			mkdir($dir); 
			showMsg("成功创建文件夹：".$dir);
		} 
	}
}
